-- 1번 문제 
SELECT EMP_ID , EMP_NAME , PHONE , HIRE_DATE 
FROM EMPLOYEE
WHERE DEPT_CODE = (SELECT DEPT_CODE FROM EMPLOYEE WHERE EMP_NAME = '전지연')
AND EMP_NAME <> '전지연'

-- 2번 문제
SELECT EMP_ID , EMP_NAME , PHONE , SALARY , JOB_NAME
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEE WHERE EXTRACT (YEAR FROM HIRE_DATE) > 2000)

-- 3번 문제
SELECT EMP_ID , EMP_NAME , DEPT_CODE , JOB_CODE , DEPT_TITLE, JOB_NAME
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
LEFT JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
WHERE (DEPT_CODE, JOB_CODE) = (SELECT DEPT_CODE, JOB_CODE FROM EMPLOYEE WHERE EMP_NAME = '노옹철')
AND EMP_NAME <> '노옹철'

-- 4번 문제
SELECT EMP_ID , EMP_NAME , DEPT_CODE , JOB_CODE , HIRE_DATE
FROM EMPLOYEE
WHERE (DEPT_CODE, JOB_CODE) = (SELECT DEPT_CODE, JOB_CODE FROM EMPLOYEE WHERE EXTRACT (YEAR FROM HIRE_DATE) = 2000)

-- 5번 문제
SELECT EMP_ID , EMP_NAME , DEPT_CODE , MANAGER_ID , EMP_NO, HIRE_DATE 
FROM EMPLOYEE
WHERE (DEPT_CODE, MANAGER_ID) IN (SELECT DEPT_CODE, MANAGER_ID FROM EMPLOYEE WHERE SUBSTR(EMP_NO, 1, 2) = 77 AND SUBSTR(EMP_NO, 8, 1) = 2)

-- 6번 문제
SELECT EMP_ID , EMP_NAME , NVL(DEPT_TITLE, '소속없음'), JOB_NAME, HIRE_DATE 
FROM EMPLOYEE MAIN
JOIN JOB USING (JOB_CODE)
LEFT JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
WHERE ENT_YN = 'N'
AND HIRE_DATE = (SELECT MIN(HIRE_DATE) FROM EMPLOYEE SUB WHERE SUB.DEPT_CODE = MAIN.DEPT_CODE)
ORDER BY HIRE_DATE


-- 7번 문제
SELECT EMP_ID , EMP_NAME , JOB_NAME, MONTHS_BETWEEN(SYSDATE, TO_DATE(SUBSTR(EMP_NO, 1, 6), 'RRMMDD')) / 12 나이, 
(SALARY * 12)+(SALARY * BONUS)보너스포함연봉
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)





CREATE TABLE NUM(
	NUM1 NUMBER
);


INSERT INTO NUM VALUES (1);
INSERT INTO NUM VALUES (1);
INSERT INTO NUM VALUES (2);
INSERT INTO NUM VALUES (3);
INSERT INTO NUM VALUES (4);

SELECT * FROM NUM;

UPDATE NUM 
SET NUM1 = 3
WHERE NUM1 = 4;

ROLLBACK;

SELECT RANK() OVER(ORDER BY NUM1) 
FROM NUM;

SELECT DENSE_RANK() OVER(ORDER BY NUM1)
FROM NUM;












CREATE TABLE EMP_TEST
AS SELECT * FROM EMPLOYEE;


ALTER TABLE EMP_TEST ADD CONSTRAINT EMP_NAME_U UNIQUE (EMP_NAME);
ALTER TABLE EMP_COPY ADD CONSTRAINT EMP_ID_U UNIQUE (EMP_ID);

ALTER TABLE EMP_TEST DROP CONSTRAINT EMP_ID_U;

ALTER TABLE EMP_TEST RENAME CONSTRAINT EMP_NAME_U TO EMP_NAME_G;


ALTER TABLE EMP_TEST
RENAME TO EMP_COPY;


ALTER TABLE EMP_COPY MODIFY EMP_ID NOT NULL;













ALTER TABLE EMP_COPY ADD CONSTRAINT EMP_NO_U UNIQUE (EMP_NO);

ALTER TABLE EMP_COPY ADD (CNAME VARCHAR(30));

ALTER TABLE EMP_COPY 자료형크기변경(CNAME VARCHAR(20));

ALTER TABLE EMP_COPY MODIFY (CNAME VARCHAR(20));

ALTER TABLE EMP_COPY DROP COLUMN CNAME;

--LNAME 한국
ALTER TABLE EMP_COPY ADD (LNAME VARCHAR(30) DEFAULT '한국');

ALTER TABLE EMP_COPY MODIFY LNAME DEFAULT 'KOREA';

SELECT *
FROM EMP_COPY


ALTER TABLE EMP_COPY ADD CONSTRAINT EMP_ID_PK PRIMARY KEY (EMP_ID);

ALTER TABLE EMP_COPY DROP CONSTRAINT EMP_ID_U;

ALTER TABLE EMP_COPY MODIFY (EMP_ID VARCHAR(3));

ALTER TABLE EMP_COPY RENAME CONSTRAINT EMP_ID_PK TO EMP_ID_PRIMARY;

ALTER TABLE EMP_COPY RENAME COLUMN EMP_ID TO EMP_NUM;












DROP TABLE EMP_COPY;

CREATE TABLE TB1(
	TB1_PK NUMBER PRIMARY KEY,
	TB1_COL NUMBER
);


CREATE TABLE TB2(
	TB2_PK NUMBER PRIMARY KEY,
	TB2_COL NUMBER REFERENCES TB1
);

DROP TABLE TB2;

CREATE TABLE TB2(
	TB2_PK NUMBER PRIMARY KEY,
	TB2_COL NUMBER,
	CONSTRAINT TB2_COL_FK FOREIGN KEY (TB2_COL) REFERENCES TB1
);






-- TB1에 샘플 데이터 삽입
INSERT INTO TB1 VALUES(1, 100);
INSERT INTO TB1 VALUES(2, 200);
INSERT INTO TB1 VALUES(3, 300);

COMMIT;


-- TB2에 샘플 데이터 삽입
INSERT INTO TB2 VALUES(11, 1);
INSERT INTO TB2 VALUES(12, 2);
INSERT INTO TB2 VALUES(13, 3);

SELECT * FROM TB1;
SELECT * FROM TB2;


ALTER TABLE TB2 RENAME COLUMN TB2_COL TO TB2_COL_COL;
DROP TABLE TB1;


DROP TABLE TB2 CASCADE CONSTRAINT;



ROLLBACK;


COMMENT ON COLUMN TB1.TB1_PK IS '기본키';









SELECT * FROM TB1

COMMENT ON COLUMN TB1.TB1_COL IS '콜콜'










